---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app librespeed
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      librespeed:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/librespeed/speedtest
              tag: 5.4.1
            env:
              MODE: standalone

            resources:
              requests:
                cpu: 25m
                memory: 25Mi
              limits:
                memory: 50Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    ingress:
      app:
        className: external
        enabled: true
        hosts:
          - host: &host speed.${CLUSTER_INGRESS}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        tls:
          - hosts:
              - *host
