---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authentik
  namespace: flux-system
spec:
  targetNamespace: security
  commonMetadata:
    labels:
      app.flux-system.io/name: *app
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: dragonfly-cluster
    - name: maddy
    - name: nginx-external
  path: ./kubernetes/main/apps/security/authentik/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: bot-box
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authentik-resources
  namespace: flux-system
spec:
  targetNamespace: flux-system
  commonMetadata:
    labels:
      app.flux-system.io/name: *app
  dependsOn:
    - name: authentik
  path: ./kubernetes/main/apps/security/authentik/resources
  prune: false
  sourceRef:
    kind: GitRepository
    name: bot-box
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
