---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rallly
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/main/apps/default/rallly/app
  dependsOn:
    - name: nginx-external
    - name: cloudnative-pg
  prune: true
  sourceRef:
    kind: GitRepository
    name: bot-box
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
