---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: authentik-secret
    template:
      engineVersion: v2
      data:
        # App
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_POSTGRESQL__NAME: &dbName authentik
        AUTHENTIK_POSTGRESQL__HOST: &dbHost postgres-rw.database.svc.${CLUSTER_DOMAIN}
        AUTHENTIK_POSTGRESQL__USER: &dbUser "{{ .AUTHENTIK_POSTGRESQL__USER }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: &dbPass "{{ .AUTHENTIK_POSTGRESQL__PASSWORD }}"
        AUTHENTIK_REDIS__HOST: dragonfly.database.svc.${CLUSTER_DOMAIN}
        AUTHENTIK_REDIS__PORT: "6379"
        AUTHENTIK_REDIS__DB: "1" # AU
        AUTHENTIK_EMAIL__FROM: Authentik <auth@{{ .SMTP_RELAY_HOSTNAME }}>

        MAXMIND_ACCOUNT_ID: "{{ .MAXMIND_ACCOUNT_ID }}"
        MAXMIND_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: 856528bf-8a4c-415a-959b-7924a813dccd # Authentik
    - extract:
        key: 18f20c46-e3c7-4fd4-afdc-80bb95b117c8 # Maxmind
    - extract:
        key: 36f9f9b7-5eea-430f-bb2c-1a61eab2e9ac # Maddy

  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: &PGkeyRef 2ab16ec4-5e9a-4d4a-a631-d7cda45ac903
        property: password
      sourceRef: &CNPGSource
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: POSTGRES_SUPER_USER
      sourceRef: *CNPGSource
      remoteRef:
        key: *PGkeyRef
        property: username
