---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: cloudnative-pg-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        POSTGRES_PASSWORD: |-
          {{ .password }}
        POSTGRES_USER: |-
          {{ .username }}
        AWS_SECRET_ACCESS_KEY: |-
          {{ .AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: |-
          {{ .AWS_ACCESS_KEY_ID }}

  dataFrom:
    - extract:
        key: fea7c5bf-1838-42db-8156-5c7c493d3daa # cloudflare-r2
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
  data:
    - secretKey: password
      remoteRef:
        key: &keyRef 2ab16ec4-5e9a-4d4a-a631-d7cda45ac903
        property: password
    - secretKey: username
      remoteRef:
        key: *keyRef
        property: username
