---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rallly
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: rallly-secret
    template:
      engineVersion: v2
      data:
        DATABASE_URL: postgres://{{ .RALLLY_DB_USERNAME }}:{{ .RALLLY_DB_PASSWORD }}@postgres-rw.database.svc.${CLUSTER_DOMAIN}:5432/rallly
        SECRET_PASSWORD: "{{ .RALLLY_SECRET }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: rallly
        INIT_POSTGRES_HOST: postgres-rw.database.svc.${CLUSTER_DOMAIN}
        INIT_POSTGRES_USER: "{{ .RALLLY_DB_USERNAME }}"
        INIT_POSTGRES_PASS: "{{ .RALLLY_DB_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: 50ece848-5210-40ad-8c20-e916e10bd4dc # Rallly
    - extract:
        key: 36f9f9b7-5eea-430f-bb2c-1a61eab2e9ac # Maddy

  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: &PGkeyRef 2ab16ec4-5e9a-4d4a-a631-d7cda45ac903
        property: password
      sourceRef: &CNPGSource
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: POSTGRES_SUPER_USER
      sourceRef: *CNPGSource
      remoteRef:
        key: *PGkeyRef
        property: username
