---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: cloudflare-api-token
    template:
      engineVersion: v2
      data:
        api-token: "{{ .CLOUDFLARE_API_TOKEN }}"
  dataFrom:
    - extract:
        key: 4af3fc95-6699-4928-b034-53c42b070b9b
