---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-external-secrets
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: cluster-external-secrets
    template:
      engineVersion: v2
      data:
        MADDY_SERVER: "{{ .SMTP_RELAY_SERVER }}"
  dataFrom:
    - extract:
        key: 36f9f9b7-5eea-430f-bb2c-1a61eab2e9ac # Maddy
