apiVersion: v1
data:
  BITWARDEN_URL: ENC[AES256_GCM,data:AgDDBneUM14p4GPUnssyvi75XjU=,iv:LiSPSPE3Vr7Hqz9rCGei+IDFFILpwL2iUSq7zTTDncI=,tag:Ye0z2g+WktY8ewOpeVKHpw==,type:str]
  CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:8KyiHAIwJzOmq9joz2owj29A1VZMAWxO6DX9tSTz5lfmwiRENWlUj69UsIU=,iv:B/xngGiNY7bYzsRv+ajPIyFcWSyXPF0nvG7hDSu9FPE=,tag:XPyOWA3Ie0ctkDwQfv2p8w==,type:str]
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age177gyd2vg9mj7unxfygrduq30t0u6s70hewhejmmcufx0re7vuvkq4sf3f8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQ3RkZ3MvTTJJZW5zbEoy
        cHI5VFJyT1dDdUtIUEdkVldXdVdvZ3JzM20wClBsc1Y5WEVCa1lOcXg2b0RIalJz
        bml6U1ltcnV5RlVuWU00bUJRNEtoeTAKLS0tIHdEclg5ZFVnMysxNGFYVkJDakVv
        dGRQNEQvelM3bFhDWVJJQ2UrQUhiOG8KBekag/IGljlaMsUqsU2+9d9F2iggejB9
        imGwm6rWo+VD8MsTANuKolWcW+N8s49Dk1Te37OGo/NRiabL4ahtiw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-14T13:24:54Z"
  mac: ENC[AES256_GCM,data:TAZoJFBn+hw1SfueqTO8M7nI/oQNjRuXOIU1tWS2YJXIB8Mvb7InnN5CpByk1rEDwM87hain2LE9i0pssYrvunG7Yxh8yzfySH5lr8ySN5g8C73iTxGXBHYZf8Niy2znI2EokS1/XqX4BYwAKLNc1qftRA47PNljRfQRlJBYzlU=,iv:QEnvI/9RB35UyBotjCX9OCDjK/NxrRrGGPC1xzGIWlg=,tag:tua7tksTNWgup/Hgu8P//g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
