---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: external-dns-cloudflare-secret
    template:
      engineVersion: v2
      data:
        CF_API_EMAIL: "{{ .CLOUDFLARE_EMAIL }}"
        CF_API_TOKEN: "{{ .CLOUDFLARE_API_TOKEN }}"
  dataFrom:
    - extract:
        key: 4af3fc95-6699-4928-b034-53c42b070b9b
