---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-cloudflare
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider: cloudflare
    env:
      - name: &name CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: &secret external-dns-cloudflare-secret
            key: *name
      - name: &name CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: *secret
            key: *name
    extraArgs:
      - --ingress-class=external
      - --cloudflare-proxied
      - --zone-id-filter=${CLOUDFLARE_ZONE_ID}
    policy: sync
    logLevel: debug
    sources: [ingress]
    txtOwnerId: default
    txtPrefix: k8s.
    domainFilters:
      - ${CLUSTER_INGRESS}
    serviceMonitor:
      enabled: ${KPS_ENABLED}
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
