---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik.yaml
  - ./backube.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./democratic-csi.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./piraeus.yaml
  - ./stakater.yaml
