---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-tofu
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: authentik-tofu-secret
    template:
      engineVersion: v2
      data:
        AUTHENTIK_URL: http//authentik-server.security.svc.${CLUSTER_DOMAIN}
        AUTHENTIK_TOKEN: "{{ .AUTHENTIK_TOKEN }}"
        AUTHENTIK_INSECURE: "true"
        TF_VAR_discord_client_id: "{{ .DISCORD_CLIENT_ID }}"
        TF_VAR_discord_client_secret: "{{ .DISCORD_SECRET }}"
        TF_VAR_discord_guild_id: "{{ .DISCORD_GUILD_ID }}"

  dataFrom:
    - extract:
        key: 856528bf-8a4c-415a-959b-7924a813dccd # Authentik
    - extract:
        key: 89f5f17e-3b24-49da-b8ce-f1a1bf2c20c3 # Discord
