---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: roxedus-net-site
spec:
  secretName: roxedus-net-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: ${CLUSTER_INGRESS}
  dnsNames:
    - ${CLUSTER_INGRESS}
    - "*.${CLUSTER_INGRESS}"
